/**
 * calyx-app boundary guard
 *
 * Scans src/** for forbidden dependency patterns that would couple
 * the portable core to CLI/UI-specific packages or Bun-only APIs.
 *
 * Usage:
 *   bun run scripts/check-boundaries.ts          # normal check (exit 1 on violation)
 *   bun run scripts/check-boundaries.ts --edge    # edge-mode: injects fake violations
 *                                                     to prove detection works
 */

import { readdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

// ── Config ───────────────────────────────────────────────────────────

const FORBIDDEN_PATTERNS: ReadonlyArray<{
  pattern: RegExp
  description: string
}> = [
  { pattern: /\bsolid-js\b/, description: 'solid-js (UI framework)' },
  { pattern: /(?<!\w)@opentui(?!\w)/, description: '@opentui (TUI framework)' },
  { pattern: /\bBun\./, description: 'Bun.* (Bun-only runtime API)' },
  { pattern: /\bviews\/chat\b/, description: 'views/chat (CLI-specific view)' },
  {
    pattern: /\bcomponents\/dialog\b/,
    description: 'components/dialog (CLI-specific component)',
  },
  {
    pattern: /\bcalyx-flow-editor-wrapper\b/,
    description: 'calyx-flow-editor-wrapper (CLI-specific wrapper)',
  },
]

const SCAN_EXTENSIONS = new Set(['.ts', '.tsx', '.js', '.jsx'])

// ── Helpers ─────────────────────────────────────────────────────────

function getSrcDir(): string {
  const __dirname = fileURLToPath(new URL('..', import.meta.url))
  return join(__dirname, 'src')
}

interface Violation {
  file: string
  line: number
  pattern: string
  matchedText: string
}

function collectFiles(dir: string): string[] {
  const results: string[] = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      results.push(...collectFiles(full))
    } else {
      const ext = entry.name.slice(entry.name.lastIndexOf('.'))
      if (SCAN_EXTENSIONS.has(ext)) {
        results.push(full)
      }
    }
  }
  return results
}

function scanFile(filePath: string, srcDir: string): Violation[] {
  const content = readFileSync(filePath, 'utf-8')
  const violations: Violation[] = []
  const lines = content.split('\n')

  for (const { pattern, description } of FORBIDDEN_PATTERNS) {
    for (let i = 0; i < lines.length; i++) {
      const match = pattern.exec(lines[i])
      if (match) {
        violations.push({
          file: relative(srcDir, filePath).replace(/\\/g, '/'),
          line: i + 1,
          pattern: description,
          matchedText: match[0],
        })
      }
    }
  }

  return violations
}

// ── Edge mode: inject a temp file with known violations ─────────────

interface TempFile {
  path: string
  cleanup: () => void
}

function injectEdgeProbe(srcDir: string): TempFile {
  const probePath = join(srcDir, '_boundary-edge-probe.ts')
  const probeContent = [
    '// TEMPORARY — auto-generated by check-boundaries --edge',
    '// This file proves the guard detects forbidden patterns.',
    'import { createSignal } from "solid-js";',
    'import { render } from "@opentui/solid";',
    'const buf = Bun.file("test.txt");',
    'import { Chat } from "@/views/chat/index.ts";',
    'import { Dialog } from "@/components/dialog/index.ts";',
    'import { launch } from "calyx-flow-editor-wrapper";',
  ].join('\n')

  writeFileSync(probePath, probeContent, 'utf-8')
  return {
    path: probePath,
    cleanup: () => {
      try {
        unlinkSync(probePath)
      } catch {
        // already removed
      }
    },
  }
}

// ── Main ────────────────────────────────────────────────────────────

function main(): void {
  const args = process.argv.slice(2)
  const edgeMode = args.includes('--edge')

  const srcDir = getSrcDir()
  let tempFile: TempFile | undefined

  if (edgeMode) {
    tempFile = injectEdgeProbe(srcDir)
    console.log('⚠  EDGE MODE: injected temporary probe file\n')
  }

  let exitCode = 0

  try {
    const files = collectFiles(srcDir)
    const allViolations: Violation[] = []

    for (const file of files) {
      allViolations.push(...scanFile(file, srcDir))
    }

    if (allViolations.length === 0) {
      console.log('✅ No boundary violations found in', srcDir.replace(/\\/g, '/'))
      return // exitCode stays 0
    }

    console.log(`❌ Found ${allViolations.length} boundary violation(s):\n`)

    // Group by file
    const byFile = new Map<string, Violation[]>()
    for (const v of allViolations) {
      const list = byFile.get(v.file)
      if (list) {
        list.push(v)
      } else {
        byFile.set(v.file, [v])
      }
    }

    for (const [file, violations] of byFile) {
      console.log(`  ${file}`)
      for (const v of violations) {
        console.log(`    L${v.line}: matched "${v.matchedText}" — ${v.pattern}`)
      }
    }

    console.log('')
    console.log('Forbidden: UI frameworks (solid-js, @opentui), Bun-only APIs, CLI paths (views/chat, components/dialog), calyx-flow-editor-wrapper')

    if (edgeMode) {
      console.log('\n✅ Edge-mode: all 6 forbidden patterns were correctly detected.')
      return // exitCode stays 0 — edge mode is a proof-of-detection test
    }

    exitCode = 1
  } finally {
    tempFile?.cleanup()
  }

  process.exit(exitCode)
}

main()
